import type { Metadata } from "next";
import AppProviders from "@/components/app-providers/app-providers";
import HeaderTemplate from "@/templates/header-template/header-template";
import MarkingMainComponents from "@/components/layouts/marking-main-components/marking-main-components";
import MainContentLayout from "@/components/layouts/main-content-layout/main-content-layout";
import "./reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="ru">
      <body>
        <AppProviders>
          <MarkingMainComponents>
            <HeaderTemplate />
            <MainContentLayout sx={{ height: "90vh" }}>
              {children}
            </MainContentLayout>
          </MarkingMainComponents>
        </AppProviders>
      </body>
    </html>
  );
};

export default RootLayout;
